#encoding: utf-8
Categoria.find_or_create_by_nombre('Aire acondicionado', :clase_css => 'aa', :descripcion => 'Instalación, mantenimiento y reparación de sistemas de refrigeración por aire acondicionado.')
Categoria.find_or_create_by_nombre('Arquitectura, Diseño y Decoración', :clase_css => 'deco', :descripcion => 'Planificación, diseño, proyección y decoración de estructuras y espacios.')
Categoria.find_or_create_by_nombre('Artículos eléctricos y electrónicos', :clase_css => 'electro', :descripcion => 'Instalación, mantenimiento y reparación de artículos eléctricos y electrónicos.')
Categoria.find_or_create_by_nombre('Carpintería y Ebanistería', :clase_css => 'carp', :descripcion => 'Trabajo con la madera y sus materiales derivados para la elaboración de estructuras y muebles.')
Categoria.find_or_create_by_nombre('Cerrajería', :clase_css => 'herre', :descripcion => 'Instalación, reparación y mantenimiento de cerraduras, candados, cerrojos y cilindros.')
Categoria.find_or_create_by_nombre('Computadores y Teléfonos', :clase_css => 'comp', :descripcion => 'Instalación, mantenimiento y reparación de computadores, teléfonos y equipos informáticos.')
Categoria.find_or_create_by_nombre('Construcción y Remodelación General', :clase_css => 'constru', :descripcion => 'Planificación, fabricación, mantenimiento y modificación de estructuras arquitectónicas.')
Categoria.find_or_create_by_nombre('Electricidad', :clase_css => 'electric', :descripcion => 'Instalación y mantenimiento de sistemas y cableados eléctricos.')
Categoria.find_or_create_by_nombre('Electrodomésticos', :clase_css => 'elecdom', :descripcion => 'Instalación, mantenimiento y reparación de electrodomésticos.')
Categoria.find_or_create_by_nombre('Fumigación', :clase_css => 'fumig', :descripcion => 'Exterminación y control de plagas animales, vegetales y de insectos')
Categoria.find_or_create_by_nombre('Herrería', :clase_css => 'herrer', :descripcion => 'Trabajo del hierro y otros metales.')
Categoria.find_or_create_by_nombre('Impermeabilización', :clase_css => 'impermeab', :descripcion => 'Revestimiento y protección de estructuras, espacios y objetos ante filtraciones.')
Categoria.find_or_create_by_nombre('Jardinería', :clase_css => 'jardin', :descripcion => 'Decoración, mantenimiento y cuidado de jardines y plantas de interior.')
Categoria.find_or_create_by_nombre('Limpieza y Servicio doméstico', :clase_css => 'limp', :descripcion => 'Mantenimiento, organización y cuidado general de espacios.')
Categoria.find_or_create_by_nombre('Mecánica automotriz', :clase_css => 'autos', :descripcion => 'Mantenimiento y reparación de vehículos automotrices.')
Categoria.find_or_create_by_nombre('Pintura', :clase_css => 'pintu', :descripcion => 'Revestimiento decorativo de paredes, techos y otras estructuras.')
Categoria.find_or_create_by_nombre('Pisos y Topes', :clase_css => 'pisos', :descripcion => 'Instalación y mantenimiento de topes y pisos.')
Categoria.find_or_create_by_nombre('Plomería', :clase_css => 'plomer', :descripcion => 'Instalación, mantenimiento y reparación de redes de tuberías para el abastecimiento de agua potable y evacuación de aguas residuales.')
Categoria.find_or_create_by_nombre('Puertas y Rejas', :clase_css => 'puert', :descripcion => 'Instalación, mantenimiento y reparación de puertas, rejas y cercas.')
Categoria.find_or_create_by_nombre('Remodelaciones de cocinas', :clase_css => 'cocin', :descripcion => 'Trabajos de restauración y reforma de cocinas.')
Categoria.find_or_create_by_nombre('Remodelaciones de baños', :clase_css => 'banos', :descripcion => 'Trabajos de restauración y reforma de baños.')
Categoria.find_or_create_by_nombre('Tapicería y Cortinas', :clase_css => 'tapicer', :descripcion => 'Instalación, mantenimiento y restauración de cortinas y muebles tapizados.')
Categoria.find_or_create_by_nombre('Techos y Toldos', :clase_css => 'techos', :descripcion => 'Instalación, mantenimiento y reparación de techos y toldos.')
Categoria.find_or_create_by_nombre('Transporte y Mudanzas', :clase_css => 'mudan', :descripcion => 'Embalaje, transporte y movilización de bienes.')
Categoria.find_or_create_by_nombre('Ventanas y Persianas', :clase_css => 'ventan', :descripcion => 'Instalación, mantenimiento y reparación de ventanas y persianas.')